# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AiratTop"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/AiratTop"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/AiratTop"

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/airat.top/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/AiratTop"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "youtube"
name = "LinkedIn"
url = "https://www.youtube.com/@AiratTop"

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "tiktok"
name = "TikTok"
url = "https://www.tiktok.com/@airat.top"

[social.params]
icon = "brand-tiktok"