# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.ico"

[footer]
# since = 2014
customText = ""

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ðŸ”¥"
subtitle = "Helping businesses scale with AI-powered process automation and custom no-code/low-code applications"

[sidebar.avatar]
enabled = true
local = true
src = "img/airattop.jpg"

[article]
headingAnchor = false
math = false
readingTime = true

[article.license]
enabled = true
default = "All Rights Reserved"

## Widgets
[[widgets.homepage]]
type = "search"

# [[widgets.homepage]]
# type = "archives"

# [widgets.homepage.params]
# limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[[widgets.page]]
type = "categories"

[widgets.page.params]
limit = 10

[[widgets.page]]
type = "tag-cloud"

[widgets.page.params]
limit = 10

[opengraph.twitter]
site = "AiratTop"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = true
src = "img/airattop.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "AiratTop/blog-comments"
repoID = "R_kgDOQLzwDA"
category = "General"
categoryID = "DIC_kwDOQLzwDM4CxPVp"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark_dimmed"
reactionsEnabled = 1
emitMetadata = 0
inputPosition = "top"
# loading = "lazy"
lang = "en"
strict = 0
